name: Semgrep

on:
  pull_request:
  push:
    branches: [ main ]

permissions:
  contents: read

jobs:
  semgrep:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Run Semgrep (curated CI rules)
        uses: returntocorp/semgrep-action@v1
        with:
          config: p/ci
          generateSarif: true
        env:
          SEMGREP_APP_TOKEN: ""
        continue-on-error: true

      - name: Upload SARIF artifact
        uses: actions/upload-artifact@v4
        with:
          name: semgrep-sarif
          path: semgrep.sarif